# Site settings
title: Leo K. Tam Blog
email: leot@nvidia.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m Leo, formerly at NVIDIA and before that Stanford.
  Take with a grain of salt some thoughts on AI and related events.
url: "http://leotam.github.io" # the base hostname & protocol for your site
twitter_username: LeoKTam
github_username:  leotam

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-80714260-1
