# Site settings
title: Leo K. Tam Blog
email: leot@nvidia.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m Leo, Medical Imaging Research Scientist @NVIDIA.
  Take with a grain of salt some thoughts on DL and related events.
  The views are solely my own and do not necessarily represent those of NVIDIA corporation.
url: "http://leotam.github.io" # the base hostname & protocol for your site
twitter_username: LeoKTam
github_username:  leotam

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-80714260-1
