# Site settings
title: Deep Learning Community Manager NVIDIA NALA
email: leot@nvidia.com
description: > # this means to ignore newlines until "baseurl:"
	Hi, I’m Leo, the Deep Learning Community Manager at NVIDIA NALA.  
	Take with a grain of salt my latest thoughts on DL and updates on events.  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leotam.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
